--- 
id: basics
name: Remix基础知识
summary: Remix中的典型工作流程
level: 1
tags: 
  - Remix
steps:
  - name: 界面介绍
    path: interface_introduction
  - name: 工作区介绍
    path: workspaces
  - name: 加载和编译
    path: load_and_compile
  - name: 部署到Remix VM
    path: deploy_to_the_remixvm
  - name: 与函数交互
    path: interacting
  - name: 部署到公共网络
    path: deploy_injected