--- 
id: tokenCourse
name: Solidity ERC20 Token课程
summary: 学习如何创建你自己的ERC20代币。本课程由p2p学习平台https://dacade.org开发。
level: 1
tags: 
  - Solidity
  - Tokens
  - ERC20
steps:
  - name: 1. 简介
    path: introduction
  - name: 2. 接口
    path: erc20-interface
  - name: 3. 创建Token
    path: erc20-token-creation
  - name: 4. 交互
    path: erc20-interaction
  - name: 5. 测试网部署
    path: erc20-testnet-deployment
  - name: 6. 扩展
    path: erc20-extensions