--- 
id: useofweb3js
name: web3.js的基础使用
summary: 本教程简要介绍了web3.js库，查询区块号。
level: 2
tags: 
  - JS
  - Remix
  - Web3
steps:
  - name: 1. 使用Web3
    path: 1_Using_Web3
  - name: 2. 查询合约
    path: 2_Querying_a_Contract