--- 
id: er721Auction
name: Contrato de subasta NFT
summary: Aprenda a escribir un contrato de subasta ERC721 (NFT). Desarrollados por la plataforma educativa p2p https://dacade.org.
level: 2
tags: 
  - Solidity
  - Tokens
  - NFT
steps:
  - name: Configuración del Contrato
    path: auction-contract-setup
  - name: Funciones Start y Bid 
    path: auction-start-bid
  - name: Funciones Withdraw y End
    path: auction-withdraw-end