--- 
id: er721Auction
name: NFT拍卖合约
summary: 学习如何编写一个ERC721拍卖合约。本课程由p2p学习平台https://dacade.org进行开发。
level: 2
tags: 
  - Solidity
  - Tokens
  - NFT
steps:
  - name: 合约设计
    path: auction-contract-setup
  - name: Start和Bid函数
    path: auction-start-bid
  - name: Withdraw和End函数
    path: auction-withdraw-end