--- 
id: nftTokenCourse
name: Courso de Solidity NFT
summary: Aprenda a crear sus propios NFTs (non-fungible tokens). Desarrollados por la plataforma educativa p2p https://dacade.org..
level: 1
tags: 
  - Solidity
  - Tokens
  - NFT
steps:
  - name: 1. Introducción
    path: introduction
  - name: 2. Interfaz
    path: erc721-interface
  - name: 3. Interfaz de Metadata
    path: erc721-interface-metadata
  - name: 4. Creación de Tokens
    path: erc721-token-creation
  - name: 5. Metadata IPFS
    path: erc721-metadata-ipfs
  - name: 6. Despliegue a la red de prueba (Testnet)
    path: erc721-deploy-testnet-opensea